### ISSUE TITLE
Generating private key process does not finish

### ISSUE THREAD

**Issue by psanders1** [arlolra/ctypes-otr#65] opened 2016-01-30 14:05 UTC
Hi,

I have installed Tor Messenger and I created an XMPP account (jabber.calyxinstitute.org), but I am unable to create the private key by OTR preferences screen. the system is waiting a long time and does not finish the process.
My operating system is Windows 10.

Please help me.

Regards

**Comment by arlolra** [comment] 2016-01-30 17:38
Thanks for reporting the issue.

After attempting to generate the key, can you check `Tools > Error Console` for any errors?
Are you using a VM?
Are you able to generate a key with Pidgin on that machine?
Did you try moving around the mouse / mashing the keyboard to provide some entropy to the system?
Are you doing this immediately after system boot?

Sorry for all the questions. Trying to gather information.

**Comment by psanders1** [comment] 2016-01-30 19:52
Thank you for your feedback!
Here are the information warning and errors. 

Information: 
=========
Tor WARN: Failed to find node for hop 0 of our path. Discarding this circuit. 
-----------------------------------------------------------------------------------------------------

Warning:
=======
Timestamp: 30/01/2016 17:31:12
Warning: Unhandled presence stanza.
Source File: resource:///modules/xmpp.jsm
Line: 1276
Source Code:
prpl-jabber: XMPPAccountPrototype.onPresenceStanza
---------------------------------------------------------------------------------

Errors:
=====
After attempting to generate the key, can you check Tools > Error Console for any errors?
Timestamp: 30/01/2016 15:11:13
Error: TypeError: this._idleService is undefined
Source File: jar:file:///C:/Users/S%C3%A9rgio/Documents/Tor%20Messenger/Messenger/omni.ja!/components/imCore.js
Line: 128

/* This Source Code Form is subject to the terms of the Mozilla Public
 * License, v. 2.0. If a copy of the MPL was not distributed with this
 * file, You can obtain one at http://mozilla.org/MPL/2.0/. */

const {classes: Cc, interfaces: Ci, utils: Cu, results: Cr} = Components;
Cu.import("resource:///modules/imServices.jsm");
Cu.import("resource:///modules/imXPCOMUtils.jsm");

XPCOMUtils.defineLazyServiceGetter(this, "categoryManager",
                                   "@mozilla.org/categorymanager;1",
                                   "nsICategoryManager");

const kQuitApplicationGranted = "quit-application-granted";
const kProtocolPluginCategory = "im-protocol-plugin";

const kPrefReportIdle =        "messenger.status.reportIdle";
const kPrefUserIconFilename =  "messenger.status.userIconFileName";
const kPrefUserDisplayname =   "messenger.status.userDisplayName";
const kPrefTimeBeforeIdle =    "messenger.status.timeBeforeIdle";
const kPrefAwayWhenIdle =      "messenger.status.awayWhenIdle";
const kPrefDefaultMessage =    "messenger.status.defaultIdleAwayMessage";

const NS_IOSERVICE_GOING_OFFLINE_TOPIC = "network:offline-about-to-go-offline";
const NS_IOSERVICE_OFFLINE_STATUS_TOPIC = "network:offline-status-changed";

function UserStatus()
{
  this._observers = [];

  if (Services.prefs.getBoolPref(kPrefReportIdle))
    this._addIdleObserver();
  Services.prefs.addObserver(kPrefReportIdle, this, false);

  if (Services.io.offline)
    this._offlineStatusType = Ci.imIStatusInfo.STATUS_OFFLINE;
  Services.obs.addObserver(this, NS_IOSERVICE_GOING_OFFLINE_TOPIC, false);
  Services.obs.addObserver(this, NS_IOSERVICE_OFFLINE_STATUS_TOPIC, false);
}
UserStatus.prototype = {
  __proto__: ClassInfo("imIUserStatusInfo", "User status info"),

  unInit: function() {
    this._observers = [];
    Services.prefs.removeObserver(kPrefReportIdle, this);
    if (this._observingIdleness)
      this._removeIdleObserver();
    Services.obs.removeObserver(this, NS_IOSERVICE_GOING_OFFLINE_TOPIC);
    Services.obs.removeObserver(this, NS_IOSERVICE_OFFLINE_STATUS_TOPIC);
  },
  _observingIdleness: false,
  _addIdleObserver: function() {
    this._observingIdleness = true;
    this._idleService =
      Cc["@mozilla.org/widget/idleservice;1"].getService(Ci.nsIIdleService);
    Services.obs.addObserver(this, "im-sent", false);

    this._timeBeforeIdle = Services.prefs.getIntPref(kPrefTimeBeforeIdle);
    if (this._timeBeforeIdle < 0)
      this._timeBeforeIdle = 0;
    Services.prefs.addObserver(kPrefTimeBeforeIdle, this, false);
    if (this._timeBeforeIdle)
      this._idleService.addIdleObserver(this, this._timeBeforeIdle);
  },
  _removeIdleObserver: function() {
    if (this._timeBeforeIdle)
      this._idleService.removeIdleObserver(this, this._timeBeforeIdle);

    Services.prefs.removeObserver(kPrefTimeBeforeIdle, this);
    delete this._timeBeforeIdle;

    Services.obs.removeObserver(this, "im-sent");
    delete this._idleService;
    delete this._observingIdleness;
  },

  observe: function(aSubject, aTopic, aData) {
    if (aTopic == "nsPref:changed") {
      if (aData == kPrefReportIdle) {
        let reportIdle = Services.prefs.getBoolPref(kPrefReportIdle);
        if (reportIdle && !this._observingIdleness)
          this._addIdleObserver();
        else if (!reportIdle && this._observingIdleness)
        this._removeIdleObserver();
      }
      else if (aData == kPrefTimeBeforeIdle) {
        let timeBeforeIdle = Services.prefs.getIntPref(kPrefTimeBeforeIdle);
        if (timeBeforeIdle != this._timeBeforeIdle) {
          if (this._timeBeforeIdle)
            this._idleService.removeIdleObserver(this, this._timeBeforeIdle);
          this._timeBeforeIdle = timeBeforeIdle;
          if (this._timeBeforeIdle)
            this._idleService.addIdleObserver(this, this._timeBeforeIdle);
        }
      }
      else
        throw Cr.NS_ERROR_UNEXPECTED;
    }
    else if (aTopic == NS_IOSERVICE_GOING_OFFLINE_TOPIC)
      this.offline = true;
    else if (aTopic == NS_IOSERVICE_OFFLINE_STATUS_TOPIC && aData == "online")
      this.offline = false;
    else
      this._checkIdle();
  },

  _offlineStatusType: Ci.imIStatusInfo.STATUS_AVAILABLE,
  set offline(aOffline) {
    let statusType = this.statusType;
    let statusText = this.statusText;
    if (aOffline)
      this._offlineStatusType = Ci.imIStatusInfo.STATUS_OFFLINE;
    else
      delete this._offlineStatusType;
    if (this.statusType != statusType || this.statusText != statusText)
      this._notifyObservers("status-changed", this.statusText);
  },

  _idleTime: 0,
  get idleTime() this._idleTime,
  set idleTime(aIdleTime) {
    this._idleTime = aIdleTime;
    this._notifyObservers("idle-time-changed", aIdleTime);
  },
  _idle: false,
  _idleStatusText: "",
  _idleStatusType: Ci.imIStatusInfo.STATUS_AVAILABLE,
  _checkIdle: function() {
    let idleTime = Math.floor(this._idleService.idleTime / 1000);
    let idle = this._timeBeforeIdle && idleTime >= this._timeBeforeIdle;
    if (idle == this._idle)
      return;

    let statusType = this.statusType;
    let statusText = this.statusText;
    this._idle = idle;
    if (idle) {
      this.idleTime = idleTime;
      if (Services.prefs.getBoolPref(kPrefAwayWhenIdle)) {
        this._idleStatusType = Ci.imIStatusInfo.STATUS_AWAY;
        this._idleStatusText =
          Services.prefs.getComplexValue(kPrefDefaultMessage,
                                         Ci.nsIPrefLocalizedString).data;
      }
    }
    else {
      this.idleTime = 0;
      delete this._idleStatusType;
      delete this._idleStatusText;
    }
    if (this.statusType != statusType || this.statusText != statusText)
      this._notifyObservers("status-changed", this.statusText);
  },

  _statusText: "",
  get statusText() this._statusText || this._idleStatusText,
  _statusType: Ci.imIStatusInfo.STATUS_AVAILABLE,
  get statusType() Math.min(this._statusType, this._idleStatusType, this._offlineStatusType),
  setStatus: function(aStatus, aMessage) {
    if (aStatus != Ci.imIStatusInfo.STATUS_UNKNOWN)
      this._statusType = aStatus;
    if (aStatus != Ci.imIStatusInfo.STATUS_OFFLINE)
      this._statusText = aMessage;
    this._notifyObservers("status-changed", aMessage);
  },

  _getProfileDir: function()
    Services.dirsvc.get("ProfD", Ci.nsIFile),
  setUserIcon: function(aIconFile) {
    let folder = this._getProfileDir();

    let newName = "";
    if (aIconFile) {
      // Get the extension (remove trailing dots - invalid Windows extension).
      let ext = aIconFile.leafName.replace(/.*(\.[a-z0-9]+)\.*/i, "$1");
      // newName = userIcon-<timestamp(now)>.<aIconFile.extension>
      newName = "userIcon-" + Math.floor(Date.now() / 1000) + ext;

      // Copy the new icon file to newName in the profile folder.
      aIconFile.copyTo(folder, newName);
    }

    // Get the previous file name before saving the new file name.
    let oldFileName = Services.prefs.getCharPref(kPrefUserIconFilename);
    Services.prefs.setCharPref(kPrefUserIconFilename, newName);

    // Now that the new icon has been copied to the profile directory
    // and the pref value changed, we can remove the old icon. Ignore
    // failures so that we always fire the user-icon-changed notification.
    try {
      if (oldFileName) {
        folder.append(oldFileName);
        if (folder.exists())
          folder.remove(false);
      }
    } catch (e) {
      Cu.reportError(e);
    }

    this._notifyObservers("user-icon-changed", newName);
  },
  getUserIcon: function() {
    let filename = Services.prefs.getCharPref(kPrefUserIconFilename);
    if (!filename)
      return null; // No icon has been set.

    let file = this._getProfileDir();
    file.append(filename);

    if (!file.exists()) {
      Services.console.logStringMessage("Invalid userIconFileName preference");
      return null;
    }

    return Services.io.newFileURI(file);
  },

  get displayName() Services.prefs.getComplexValue(kPrefUserDisplayname,
                                                   Ci.nsISupportsString).data,
  set displayName(aDisplayName) {
    let str = Cc["@mozilla.org/supports-string;1"]
              .createInstance(Ci.nsISupportsString);
    str.data = aDisplayName;
    Services.prefs.setComplexValue(kPrefUserDisplayname, Ci.nsISupportsString,
                                   str);
    this._notifyObservers("user-display-name-changed", aDisplayName);
  },

  addObserver: function(aObserver) {
    if (this._observers.indexOf(aObserver) == -1)
      this._observers.push(aObserver);
  },
  removeObserver: function(aObserver) {
    this._observers = this._observers.filter(function(o) o !== aObserver);
  },
  _notifyObservers: function(aTopic, aData) {
    for each (let observer in this._observers)
      observer.observe(this, aTopic, aData);
  }
};

var gCoreService;
function CoreService() { gCoreService = this; }
CoreService.prototype = {
  globalUserStatus: null,

  _initialized: false,
  get initialized() this._initialized,
  init: function() {
    if (this._initialized)
      return;

    initLogModule("core", this);

    Services.obs.addObserver(this, kQuitApplicationGranted, false);
    this._initialized = true;

    Services.cmd.initCommands();
    this._protos = {};

    this.globalUserStatus = new UserStatus();
    this.globalUserStatus.addObserver({
      observe: function(aSubject, aTopic, aData) {
        Services.obs.notifyObservers(aSubject, aTopic, aData);
      }
    });

    let accounts = Services.accounts;
    accounts.initAccounts();
    Services.contacts.initContacts();
    Services.conversations.initConversations();
    Services.obs.notifyObservers(this, "prpl-init", null);

    // Wait with automatic connections until the password service
    // is available.
    if (accounts.autoLoginStatus == Ci.imIAccountsService.AUTOLOGIN_ENABLED) {
      Services.logins.initializationPromise.then(() => {
        Services.accounts.processAutoLogin();
      });
    }
  },
  observe: function(aObject, aTopic, aData) {
    if (aTopic == kQuitApplicationGranted)
      this.quit();
  },
  quit: function() {
    if (!this._initialized)
      throw Cr.NS_ERROR_NOT_INITIALIZED;

    Services.obs.removeObserver(this, kQuitApplicationGranted);
    Services.obs.notifyObservers(this, "prpl-quit", null);

    Services.conversations.unInitConversations();
    Services.accounts.unInitAccounts();
    Services.contacts.unInitContacts();
    Services.cmd.unInitCommands();

    this.globalUserStatus.unInit();
    delete this.globalUserStatus;
    delete this._protos;
    delete this._initialized;
  },

  getProtocols: function() {
    if (!this._initialized)
      throw Cr.NS_ERROR_NOT_INITIALIZED;

    let protocols = [];
    let entries = categoryManager.enumerateCategory(kProtocolPluginCategory);
    while (entries.hasMoreElements()) {
      let id = entries.getNext().QueryInterface(Ci.nsISupportsCString).data;

      // If the preference is set to disable this prpl, don't show it in the
      // full list of protocols.
      let pref = "chat.prpls." + id + ".disable";
      if (Services.prefs.getPrefType(pref) == Services.prefs.PREF_BOOL &&
          Services.prefs.getBoolPref(pref)) {
        this.LOG("Disabling prpl: " + id);
        continue;
      }

      let proto = this.getProtocolById(id);
      if (proto)
        protocols.push(proto);
    }
    return new nsSimpleEnumerator(protocols);
  },

  getProtocolById: function(aPrplId) {
    if (!this._initialized)
      throw Cr.NS_ERROR_NOT_INITIALIZED;

    if (this._protos.hasOwnProperty(aPrplId))
      return this._protos[aPrplId];

    let cid;
    try {
      cid = categoryManager.getCategoryEntry(kProtocolPluginCategory, aPrplId);
    } catch (e) {
      return null; // no protocol registered for this id.
    }

    let proto = null;
    try {
      proto = Cc[cid].createInstance(Ci.prplIProtocol);
    } catch (e) {
      // This is a real error, the protocol is registered and failed to init.
      let error = "failed to create an instance of " + cid + ": " + e;
      dump(error + "\n");
      Cu.reportError(error);
    }
    if (!proto)
      return null;

    try {
      proto.init(aPrplId);
    } catch (e) {
      Cu.reportError("Could not initialize protocol " + aPrplId + ": " + e);
      return null;
    }

    this._protos[aPrplId] = proto;
    return proto;
  },

  QueryInterface: XPCOMUtils.generateQI([Ci.imICoreService]),
  classDescription: "Core",
  classID: Components.ID("{073f5953-853c-4a38-bd81-255510c31c2e}"),
  contractID: "@mozilla.org/chat/core-service;1"
};

const NSGetFactory = XPCOMUtils.generateNSGetFactory([CoreService]);

Are you using a VM?
No. I am not using a Virtual Machine.

Are you able to generate a key with Pidgin on that machine?
Yes I am able to generate a key with Pidgin in the same machine.

Did you try moving around the mouse / mashing the keyboard to provide some entropy to the system?
Yes, the system is ok. The other applications are running normally, but the nothing happens with the "Generating screen".

Are you doing this immediately after system boot?
No.

**Comment by psanders1** [comment] 2016-01-31 00:01
Hi,

I have a new Error Console Message (Now after clearing the error console log): 

Timestamp: 30/01/2016 21:47:36
Error: A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Sat Jan 30 2016 21:47:34 GMT-0200 (Hora oficial do Brasil)
Full Message: Error: Generating key failed!
Full Stack: otrPriv.onload/<@chrome://otr/content/priv.js:19:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1
otrPref.generate@chrome://otr/content/prefs.js:89:5
oncommand@chrome://otr/content/prefs.xul:1:1

Source File: chrome://otr/content/priv.js
Line: 19
Source Code:
19

**Comment by arlolra** [comment] 2016-01-31 00:30
@psanders1 Nice! Thank you. Is your system 32 or 64 bit?

**Comment by psanders1** [comment] 2016-02-01 02:21
32 bit

**Comment by arlolra** [comment] 2016-02-01 17:55
I see ... well, that helps. I'll need to find a 32 bit Windows machine to test on. Thanks!

**Comment by arlolra** [comment] 2016-02-01 19:12
Hmm, I had no issues on a 32 bit Windows 8 VM.

@psanders1 How adept are you at debugging? Could you add this statement `Cu.reportError(err);` on L217 (inside `handleErr`) of otr.js? And then try generating a key again?

**Comment by arlolra** [comment] 2016-02-01 19:42
@azadi Tested in a 32 bit Windows 10 VM, also no issue.

**Comment by psanders1** [comment] 2016-02-01 20:39
Here is the Error Console, the code change I did is below. Is it correct?

Timestamp: 01/02/2016 18:27:09
Error: 16810065
Source File: chrome://otr/content/otr.js
Line: 218

Timestamp: 01/02/2016 18:27:12
Error: A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Mon Feb 01 2016 18:27:09 GMT-0200 (Hora oficial do Brasil)
Full Message: Error: Generating key failed!
Full Stack: otrPriv.onload/<@chrome://otr/content/priv.js:19:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1
otrPref.generate@chrome://otr/content/prefs.js:89:5
oncommand@chrome://otr/content/prefs.xul:1:1

Source File: chrome://otr/content/priv.js
Line: 19
Source Code:
19

Code change I did:

  generatePrivateKey: function(account, protocol) {
    let newkey = new ctypes.void_t.ptr();
    let err = libOTR.otrl_privkey_generate_start(
      otr.userstate, account, protocol, newkey.address()
    );
    if (err || newkey.isNull())
      return Promise.resolve(false);
    let worker = new BasePromiseWorker("chrome://otr/content/worker.js");
    let handleErr = function(err) {
      Cu.reportError(err)
      if (!newkey.isNull())
        libOTR.otrl_privkey_generate_cancelled(otr.userstate, newkey);
      return false;
    };
    return worker.post("generateKey", [
      libOTR.path, libOTR.otrl_version, newkey.toSource()
    ]).then(function(err) {
      if (!err)
        err = libOTR.otrl_privkey_generate_finish(
          otr.userstate, newkey, otr.privateKeyPath
        );
      return err ? handleErr(err) : true;
    }).catch(handleErr);
  },

**Comment by arlolra** [comment] 2016-02-01 21:37
> the code change I did is below. Is it correct?

Yup, looks great, thanks.

So, `16810065` is a `gcry_error_t` and, unfortunately, we need to call `gcry_err_code()` on it to determine the `gcry_err_code_t`. The only thing Google points to for that particular value isn't very helpful.

https://lists.cypherpunks.ca/pipermail/otr-dev/2015-March/002323.html

I'll try and think about "next steps" here. Thanks for helping out so far.

**Comment by arlolra** [comment] 2016-02-01 21:48
> Yes I am able to generate a key with Pidgin in the same machine.

Btw, when did you last try that? Can you confirm that's still working for you now.

Can you think of anything specific to your environment that might be causing this issue?

Finally, can you download the latest version of Tor Messenger and install it in a different directory (we should keep the broken one around to try and get to the heart of the problem).

https://trac.torproject.org/projects/tor/wiki/doc/TorMessenger#Downloads

Then try generating a key again.

Sorry this isn't working out so well for you. I really appreciate your help in debugging.

**Comment by psanders1** [comment] 2016-02-02 00:50
I have just tried to generate a key with Pidgin with a new account in the same machine and it worked  as before, that is, generated the private key without any problems.

I really do not know anything specific in my environment that might be causing this isseue.

I also downloaded the latest version of Tor Messenger in a different directory and tried to generate the private key again, but the error persists.

**Comment by arlolra** [comment] 2016-02-02 02:39
Hmm, just thought of something. Can you try putting the statement on L224 as well. Like this,

```
]).then(function(err) {
Cu.reportError(err);
if (!err)
```

That'll help us distinguish whether the error is happening while generating the key in `otrl_privkey_generate_calculate` or when saving it to disk with `otrl_privkey_generate_finish`. I'm thinking it's actually the latter, and this is some sort of file permission issue.

**Comment by psanders1** [comment] 2016-02-02 14:25
Hi,

Here is the error console after changing the code:

Timestamp: 02/02/2016 12:17:57
Error: 0
Source File: chrome://otr/content/otr.js
Line: 226

Timestamp: 02/02/2016 12:17:57
Error: 16810065
Source File: chrome://otr/content/otr.js
Line: 218

Timestamp: 02/02/2016 12:18:03
Error: A promise chain failed to handle a rejection. Did you forget to '.catch', or did you forget to 'return'?
See https://developer.mozilla.org/Mozilla/JavaScript_code_modules/Promise.jsm/Promise

Date: Tue Feb 02 2016 12:17:57 GMT-0200 (Hora oficial do Brasil)
Full Message: Error: Generating key failed!
Full Stack: otrPriv.onload/<@chrome://otr/content/priv.js:19:1
Handler.prototype.process@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:934:23
this.PromiseWalker.walkerLoop@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:813:7
this.PromiseWalker.scheduleWalkerLoop/<@resource://gre/modules/Promise.jsm -> resource://gre/modules/Promise-backend.js:747:1
otrPref.generate@chrome://otr/content/prefs.js:89:5
oncommand@chrome://otr/content/prefs.xul:1:1

Source File: chrome://otr/content/priv.js
Line: 19
Source Code:
19


Regards

**Comment by arlolra** [comment] 2016-02-02 17:42
Ok, so the problem isn't generating the key, it's saving it to disk.

Where are you installing the application? What's the path? If you haven't already, try installing it on your desktop where the application would have privilege to create files.

**Comment by psanders1** [comment] 2016-02-03 18:17
I have just installed in my desktop and the problem persisted.
But you gave me a clue. My user folder is Sérgio with acute accent  ( ´ ) used in portuguese language, this acute accent may be causing the issue in the path name. So, I installed in the root directory (C:\Tor Messenger) and now everything goes right and we got the private key.

Thank you a lot for your attention and help!

**Comment by arlolra** [comment] 2016-02-03 19:01
Aha! Glad we got to the bottom of it.

I'm going to reopen the task because we can definitely improve the error messages here and we should be able to handler UTF8 paths.

**Comment by arlolra** [comment] 2016-02-04 21:28
@psanders1 I pushed a fix for this issue. Look for it in the next Tor Messenger release. Thanks again for reporting.

**Closed** 2016-02-04 21:27 UTC
Labels: bug
